// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKdQocYfUJH1AGf5QKsgVDfESbJg27n0c',
    appId: '1:124329760538:web:18a008d1691b05e1183ea3',
    messagingSenderId: '124329760538',
    projectId: 'exam-e5650',
    authDomain: 'exam-e5650.firebaseapp.com',
    storageBucket: 'exam-e5650.appspot.com',
    measurementId: 'G-RNB4GX3DM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-hOb6wkpckMdRZaUGE-j6m9H9wQkdYak',
    appId: '1:124329760538:android:4584c0e35f72d72c183ea3',
    messagingSenderId: '124329760538',
    projectId: 'exam-e5650',
    storageBucket: 'exam-e5650.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcYjSzuUPT9BGge-mluGbgX2EbkP4cqMU',
    appId: '1:124329760538:ios:ad63392891752806183ea3',
    messagingSenderId: '124329760538',
    projectId: 'exam-e5650',
    storageBucket: 'exam-e5650.appspot.com',
    iosBundleId: 'com.example.exam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcYjSzuUPT9BGge-mluGbgX2EbkP4cqMU',
    appId: '1:124329760538:ios:ad63392891752806183ea3',
    messagingSenderId: '124329760538',
    projectId: 'exam-e5650',
    storageBucket: 'exam-e5650.appspot.com',
    iosBundleId: 'com.example.exam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKdQocYfUJH1AGf5QKsgVDfESbJg27n0c',
    appId: '1:124329760538:web:03d8b2b26c3d6672183ea3',
    messagingSenderId: '124329760538',
    projectId: 'exam-e5650',
    authDomain: 'exam-e5650.firebaseapp.com',
    storageBucket: 'exam-e5650.appspot.com',
    measurementId: 'G-76CZ6C8TVF',
  );
}
